import = ["/Users/db2553/.config/alacritty/themes/base16.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 0

[window]
decorations = "none"
opacity = 1.0
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
