[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 0

[window]
opacity = 1.0
option_as_alt = "OnlyLeft"

[general]
live_config_reload = true
import = [
  '~/.config/alacritty/themes/tokyonight.toml',
  '~/.config/alacritty/os_overrides.toml'
]

[[hints.enabled]]
command = { program = "sh", args = ["-c", "$HOME/.local/bin/open-md-nvim \"$1\"", "--"] }
hyperlinks = false
post_processing = true
persist = false
mouse = { enabled = true, mods = "Shift" }
binding = { key = "o", mods = "Control|Shift" }
regex = '''(?:~|/)[^\s"'<>{}|\\^`\[\](]*\.md'''

[[hints.enabled]]
command = { program = "sh", args = ["-c", "open \"$(echo \"$1\" | sed 's|~|'\"$HOME\"'|')\"", "--"] }
hyperlinks = false
post_processing = true
persist = false
mouse = { enabled = true, mods = "None" }
binding = { key = "F", mods = "Control|Shift" }
regex = '''(?:https?://|ftp://)[^\s"'<>{}|\\^`\[\]]*|(~|/)[^\s"'<>{}|\\^`\[\](]*'''
