version: '3'
services:
  app:
    build:
      context: .
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
    depends_on:
      - webdriver_chrome
  webdriver_chrome:
    image: selenium/standalone-chrome
