#!/bin/sh
set -e
test -n "$BASH_DASHX" && set -x

cd ./config && ./setup
cd -

ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/profile" "$HOME/.profile"

mkdir -p "$HOME/.local/bin" || true

[ -z "$OS" ] && export OS=`uname`
if [ "$OS" = Darwin ]; then
  for i in hammerspoon karabiner; do
    cd $i && ./setup
    cd -
  done
fi
