#!/bin/sh

run_docker() {
  _dev=$(docker ps -a | grep dev)
  _dev_running=$(docker ps | grep dev)
  _dev_exited=$(docker ps -a | grep dev | grep Exited)

  if ! test -z "$_dev_exited"
  then
    docker start dev
    docker attach dev
  elif ! test -z "$_dev"
  then
    docker run dev
    docker attach dev
  elif ! test -z "$_dev_running"
  then
    docker attach dev
  else
    docker run -it -p 3000:3000 -h workspace --name dev workspace
  fi

  return 0
}

run_docker
