#!/bin/sh

# Place your default playlist in ~/.default_playlist
default_playlist=$(head -n 1 $HOME/.default_playlist)

playlist="${1:-$default_playlist}"
exec mpv "$playlist" --volume=40 --geometry=100%:100% --shuffle 2>/dev/null
