require:
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - !ruby/regexp /\.old\.rb$/
