require "user.globals"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.options"
require "user.providers"
require "user.builtins"

-- Plugin specific
-- Lua plugin
require "user.impatient"
require "user.treesitter"
require "user.telescope"
require "user.autopairs"
require "user.endwise"
require "user.lsp"
require "user.cmp"
require "user.surround"
require "user.gps"
require "user.lualine"
require "user.gitsigns"
require "user.nvim-web-devicons"
require "user.dap"

-- Non lua
require "user.rails"
require "user.rhubarb"
require "user.test"
require "user.vimwiki"
