#!/bin/sh

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
    nvim -E -s +PlugUpdate +qa
else
    curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +PlugUpdate +PlugClean! +qa

reset -Q
