#!/bin/sh
set -e
set -x

# This script is called from the Dockerfile ENTRYPOINT and stored in the
# root of the resulting workspace container for reference.

if test -e /var/run/been_built; then
  exec sh -c "su - $(head -1 /var/run/defuser)"
fi

_NAME="you"
_ID="1000"
_GID="1000"
_HOME="/home/you"
_SHELL="/bin/bash"
_EMAIL="you@you.u"

get_new_user_info() {
  local user userid home
  read -p "User Name ($_NAME): " user
  test -n "$user" && _NAME="$user"
  read -p "User ID ($_ID): " userid
  test -n "$userid" && _ID="$userid"
  read -p "Group ID ($_GID): " gid
  test -n "$gid" && _GID="$gid"
  read -p "User Home Directory ($_HOME): " home
  test -n "$home" && _HOME="$home"
  read -p "User Shell ($_SHELL): " shell
  test -n "$shell" && _SHELL="$shell"
  return 0
}

get_email_address() {
  local email
  read -p "Email ($_EMAIL): " email
  test -n "$email" && _EMAIL="$email"
  return 0
}

create_new_user() {
  local shell=${_SHELL##*/}
  if ! type "$shell"; then
    echo Attempting to install shell: $shell
    apt install -y "$shell"
  fi
  groupadd -g "$_GID" "$_NAME"
  useradd -m -s "$_SHELL" -d "$_HOME" -u "$_ID" -g "$_GID" "$_NAME"
  # TODO add to docker group
  apt install sudo
  echo "${_NAME} ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
}

setup_dotfiles() {
  mkdir -p "$_HOME/code"
  cd "$_HOME/code"
  git clone --branch bash "http://github.com/dblanken/dotfiles"
  cd dotfiles
  runuser -l "$_NAME" -c 'cd $HOME/code/dotfiles && ./setup'
}

been_built() {
  touch /var/run/been_built
  echo "$_NAME" >/var/run/defuser
}

create_ssh_keys() {
  runuser -l "$_NAME" -c 'ssh-keygen -t ed25519 -C "${_EMAIL}"'
  echo "Make your own ~/.config/hub file: "
  echo "  enterprise_path:"
  echo "  - user: <USERNAME>"
  echo "    oauth_token: <TOKEN>"
  echo "    protocol: https"
}

## ------------------------------- main -------------------------------

git --version

# while test ! "$a" = y; do
#   get_new_user_info
#   read -p 'Keep? ' a
#   echo $a
# done

# while test ! "$a" = y; do
#   get_email_address
#   read -p 'Keep? ' a
#   echo $a
# done

create_new_user
setup_dotfiles
# create_ssh_keys

for i in vim tmux lynx hub bash-completion; do
  "$_HOME/code/dotfiles/installers/install-$i"
done

been_built

chown -R "$_NAME:$_GID" $_HOME
exec /bin/sh -c "su - $_NAME"
