#!/bin/sh

_NAME=${1:-$USER}
_HOME=${2:-$HOME}

if [ ! -f "${_HOME}/.asdf/asdf.sh" ]; then
	echo "Install asdf first"
	return 1
fi

_VERSION=${3:-lts}

sudo apt install gpg
runuser -l "$_NAME" -c "source $_HOME/.asdf/asdf.sh && asdf plugin-add nodejs"
runuser -l "$_NAME" -c "source $_HOME/.asdf/asdf.sh && asdf install nodejs $_VERSION"

runuser -l "$_NAME" -c "source $_HOME/.asdf/asdf.sh && asdf global nodejs $_VERSION"
