#!/bin/sh

_NAME=${1:-$USER}
_HOME=${2:-$HOME}
if [ ! -f "${_HOME}/.asdf/asdf.sh" ]; then
	echo "Install asdf first"
	return 1
fi

_VERSION=${1:-2.7.3}

sudo apt install -y autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev

runuser -l "$_NAME" -c "source $_HOME/.asdf/asdf.sh && asdf plugin-add ruby"
runuser -l "$_NAME" -c "source $_HOME/.asdf/asdf.sh && asdf install ruby $_VERSION"

runuser -l "$_NAME" -c "source $_HOME/.asdf/asdf.sh && asdf global ruby $_VERSION"
