#!/bin/sh

if [ ! -f "${_HOME}/.asdf/asdf.sh" ]; then
	echo "Install asdf first"
	return 1
fi

_VERSION=${1:-lts}

sudo apt install gpg
runuser -l "$_NAME" -c "source $HOME/.asdf/asdf.sh && asdf plugin-add nodejs"
runuser -l "$_NAME" -c "source $HOME/.asdf/asdf.sh && asdf install nodejs $_VERSION"

runuser -l "$_NAME" -c "source $HOME/.asdf/asdf.sh && asdf global nodejs $_VERSION"
