#!/bin/bash

## Returns the full path to any changed files in the current directory
## or any subdirectories recursively one to a line. Useful for detecting
## changes and taking action (see onchange).

changed () {
  local dir="${PWD}"
  local tmpname="onchange${dir//\//-}"
  local tmp="/tmp/${tmpname}"
  local dirs="${1:-${dir}/app ${dir}/lib ${dir}/test}"
  if [[ ! -e "${tmp}" ]]; then
    find -f $dirs -type f
  else
    find -f $dirs -type f -newer "${tmp}" 
  fi
  touch "${tmp}"
}

changed "$@"
