#!/bin/sh

# Given a ruby file located in either app or lib, it will return the
# alternate test file associated with it.  Given a ruby test file
# located in test, it will give the ruby file associated with it.

altfile() {
  local current_file="$1"
  local dir="${PWD}"

  if [[ "$current_file" =~ _test.rb$ ]]; then
    rbfile "$current_file"
  else
    rbtestfile "$current_file"
  fi
}

altfile "$@"
