#!/bin/sh

rbtestfile() {
  local current_file="$1"

  # First statement gets any app/lib and converts it
  # Second perl statement removes app if it exists
  echo "$current_file" | perl -pe 's/^(.*)(\/?app|\/?lib)\/(.+).rb$/\1test\/\2\/\3_test.rb/' | perl -pe 's/^(.*)test\/app(.+)/\1test\2/'
}

rbtestfile "$@"
