#!/bin/sh

mkdir ~/.config/ 2>/dev/null
rm -rf ~/.config/lynx 2>/dev/null
ln -s "$PWD" "$HOME/.config/lynx"
ls -l ~/.config/lynx

echo "Now just put lynx into your PATH or update it to look like the following:"
echo ""
echo "export PATH=\"$PWD:$PATH\""
