# related to editing configuration
alias nvimrc='$EDITOR ~/.config/nvim/init.vim'
alias tmuxconf='$EDITOR ~/.tmux.conf'
alias vimrc='$EDITOR ~/.vimrc'
alias zshrc='$EDITOR ~/.zshrc'
alias bashrc='$EDITOR ~/.bash_profile'

# common commands
alias '?'='duck'
alias '??'='google'
alias '???'='bing'
# alias be='bundle exec'
# alias bi='bundle install -j 8'
# alias c='cd'
# alias g='git'
# alias ga='git add'
# alias gb='git branch'
# alias gc!='git commit -v --amend'
# alias gc='git commit -v'
# alias gca!='git commit -v -a --amend'
# alias gca='git commit -a'
# alias gcb='git checkout -b'
# alias gco='git checkout'
# alias gd='git diff'
# alias gk='\gitk --all --branches'
# alias gke='\gitk --all $(git log -g --pretty=%h)'
# alias glo='git long --oneline --decorate'
# alias glog='git log --oneline --decorate --graph'
# alias gm='git merge'
# alias gma='git merge --abort'
# alias gmtvim='git mergetool --no-prompt --tool=vimdiff'
# alias gp='git push'
# alias gpf!='git push --force'
# alias gpristine='git reset --hard && git clean -dffx'
# alias gr='git remote'
# alias grb='git rebase'
# alias grm='git rm'
# alias gst='git status'
# alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign -m "--wip-- [skip ci]"'
# alias howamidoing="history | awk '{a[\$2]++}END{for(i in a){print a[i] \" \" i}}' | sort -rn | head -20"
# alias killruby='pkill -f ruby'
# alias rubykill='killruby'
# alias u='cd ..'
# alias v='vim'
# alias x='exit'

# Docker
alias images='docker images'
alias drun='docker run -it'
alias dex='docker exec -it'

# overrides
alias cat='bat'
alias irb='irb --readline -r irb/completion'
alias ls='ls -GFh'
alias mkdir='mkdir -p'
alias vi='vim'
